version: '3.8'

services:
  seq:
    container_name: fischer-seq
    image: datalust/seq:latest
    hostname: localhost
    ports:
      - 5341:80
    environment:
        - ACCEPT_EULA=Y
    mem_limit: 512m

  postgres:
    container_name: fischer-postgres
    image: postgres:14.5
    mem_limit: 256m
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=master
    volumes:
      - fischer_postgres:/var/lib/postgresql/data
      
  redis:
    container_name: fischer-redis
    image: redis:latest
    mem_limit: 100m
    ports:
      - 6379:6379

  rabbitmq:
    container_name: fischer-rabbitmq
    image: rabbitmq:3-management
    mem_limit: 512m
    ports:
      - 5672:5672
      - 15672:15672